### ISSUE TITLE
Add option to upload to Github

### ISSUE THREAD

**Issue by vincentes** [psbrandt/generator-openmrs-owa#11]
Since there's an input for Github repository and username I think an option to create a new repository containing the generated content would be nice. This would be done using the Github API. Any thoughts on this?

**Comment by psbrandt** [comment]
How would this be different from just running `git push`?

**Comment by Vincentes** [comment]
That it would be automated. The user would just have to enter a single input instead of creating a repository and doing ``git add -A``, ``git commit -m "Initial commit"``, and ``git push origin master``. It would be for convenience, it's not really important.

**Comment by psbrandt** [comment]
I think it *might* be useful to have the option to do the following things:

- Create remote repo on GitHub
- Initialise the local repo
- [maybe] Stage local files & do first commit

I'm not sure the doing a push of a 'blank' OWA makes sense though.

What about having a gulp task called something like `git-publish` that will (optionally) create the repo if it doesn't exist and stage the files for commit, then ask the user for the commit message, then push?

**Comment by Vincentes** [comment]
Makes sense. I'll make a fork where an option is given to prepare a repository (not upload) and see how it turns out.

**Comment by vincentes** [comment]
I've been busy IRL. I'm closing this for now.
